project:
  type: book
  output-dir: docs

execute:
  cache: true

book:
  title: "Elegant and informative maps with **tmap**"
  page-footer: "Elegant and informative maps with **tmap** by Martijn Tennekes and Jakub Nowosad."
  # number-sections: true
  author: "Martijn Tennekes and Jakub Nowosad"
  description: | 
    This book teaches how to make elegant and informative maps with the R package tmap.
  # cover-image: https://geocompx.org/static/img/book_cover_py.png
  site-url: https://tmap.geocompx.org/
  repo-url: https://github.com/geocompx/tmap/
  date: now
  date-format: iso
  repo-branch: main
  repo-actions: [edit]
  # sharing: [twitter, facebook, linkedin]
  google-analytics: G-ER2GMPEJNF
  # favicon: favicon-32x32.png
  chapters:
    - "index.qmd"
    - part: "Basics"
      chapters: 
      - "XX-intro.qmd"
      - "XX-geodata.qmd" 
      - "XX-nutshell.qmd" 
      - "XX-save.qmd" 
    - part: "Building blocks"
      chapters: 
      - "XX-tm-shape.qmd" 
      - "XX-layers.qmd" 
      - "XX-visual-variables.qmd" 
      - "XX-scales.qmd"
      - "XX-attr-layers.qmd"
      - "XX-layout.qmd" 
      - "XX-interactive.qmd" 
    - part: "Expanding the toolbox"
      chapters: 
        - "XX-small-multiples.qmd" 
        - "XX-animations.qmd"
        - "XX-shiny.qmd"
        - "XX-other-types.qmd"
    - part: "Advanced topics"
      chapters:
      - "XX-options.qmd" 
    - "XX-good-maps.qmd"
    - "references.qmd"
  appendices:
    - "XX-data_processing.qmd"

format:
  html: 
    theme: [brand, flatly]
    # linkcolor: "#73A7A8"
    code-link: true
    template-partials: [helpers/toc.html, helpers/title-block.html]
    toc-title: "On this page"
    code-overflow: wrap
    toc-depth: 4
    # css: [helpers/mystyle.css]
  # pdf:
  #   documentclass: krantz
  #   monofont: 'Source Code Pro'
  #   monofontoptions: 
  #     - Scale=0.7
  #   pdf-engine: xelatex
  #   keep-tex: true
  #   number-sections: true
  #   top-level-division: chapter
  #   include-before-body: helpers/before_body.tex
  #   include-in-header: 
  #     text: |
  #       \AtBeginEnvironment{longtable}{\footnotesize}
  #       \usepackage{makeidx}
  #       \makeindex
  #   include-after-body: 
  #     text: |
  #       \printindex

bibliography: 
  - r-tmap.bib
  - packages.bib
